/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm_university;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author USER
 */
public class SecondSemResultView extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/nsbmdb";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBConection dbcon=new DBConection();
     String uid;
     String sub1;
        String sub2;
        String sub3;
        String sub4;
        String sub5;
        String sub6;
        String sub7;
        String subr1;
        String subr2;
        String subr3;
        String subr4;
        String subr5;
        String subr6;
        String subr7;
        
    /**
     * Creates new form SecondSemResultView
     */
    public SecondSemResultView() {
        initComponents();
    }

    public SecondSemResultView(String u,String name,String gjsub1,String gjsub2,String gjsub3,String kgjsub1,String kgjsub2,String kgjsub3,String kgjsub4,String gjsubr1,String gjsubr2,String gjsubr3,String kgjsubr1,String kgjsubr2,String kgjsubr3,String kgjsubr4) {
        initComponents();
        jid.setText(u);
        jname.setText(name);
        j1.setText(gjsub1);
        j2.setText(gjsub2);
        j3.setText(gjsub3);
        j4.setText(kgjsub1);
        j5.setText(kgjsub2);
        j6.setText(kgjsub3);
        j7.setText(kgjsub4);
        jr1.setText(gjsubr1);
        jr2.setText(gjsubr2);
        jr3.setText(gjsubr3);
        jr4.setText(kgjsubr4);
        jr5.setText(kgjsubr1);
        jr6.setText(kgjsubr2);
        jr7.setText(kgjsubr3);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        jr1 = new javax.swing.JLabel();
        jr2 = new javax.swing.JLabel();
        jr3 = new javax.swing.JLabel();
        jr4 = new javax.swing.JLabel();
        jr5 = new javax.swing.JLabel();
        jr6 = new javax.swing.JLabel();
        jr7 = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Result Sheet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Index No:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        j1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j1.setText("Subject1:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("2nd Semester");

        j3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j3.setText("Subject3:");

        j2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j2.setText("Subject2:");

        j4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j4.setText("Subject4:");

        j5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j5.setText("Subject5:");

        j6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j6.setText("Subject6:");

        j7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j7.setText("Subject7:");

        jr1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr1.setText("Result1");

        jr2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr2.setText("Result2");

        jr3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr3.setText("Result3");

        jr4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr4.setText("Result4");

        jr5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr5.setText("Result5");

        jr6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr6.setText("Result6");

        jr7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jr7.setText("Result7");

        jid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jid.setText("StdId");

        jname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jname.setText("Name");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Send Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1)
                            .addComponent(j7)
                            .addComponent(j6)
                            .addComponent(j5)
                            .addComponent(j4)
                            .addComponent(j3)
                            .addComponent(j2)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jname)
                            .addComponent(jid)
                            .addComponent(jr2)
                            .addComponent(jr3)
                            .addComponent(jr4)
                            .addComponent(jr5)
                            .addComponent(jr6)
                            .addComponent(jr1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jr7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jname))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1)
                    .addComponent(jr1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2)
                    .addComponent(jr2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j3)
                    .addComponent(jr3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4)
                    .addComponent(jr4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j5)
                    .addComponent(jr5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j6)
                    .addComponent(jr6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j7)
                    .addComponent(jr7)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondSemResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondSemResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondSemResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondSemResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondSemResultView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jr1;
    private javax.swing.JLabel jr2;
    private javax.swing.JLabel jr3;
    private javax.swing.JLabel jr4;
    private javax.swing.JLabel jr5;
    private javax.swing.JLabel jr6;
    private javax.swing.JLabel jr7;
    // End of variables declaration//GEN-END:variables
}
